# Most settings taken from https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
site_name: "Get Security Done - Test 4"
site_description: 'GSD test4'
site_author: 'David Caddick'
docs_dir: docs/
repo_name: 'dcaddick/gsd_test4'
repo_url: 'https://github.com/dcaddick/gsd_test4'
nav:
    - Home: README.md
theme:
  name: material
  icon: 
    repo: fontawesome/brands/git-alt
    admonition:
      <type>: octicons/alert-16 # material/alert
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
