site_name: Test docs
site_description: 'A docs test'
site_author: 'David Caddick'
docs_dir: docs/
repo_name: 'dcaddick/gsd_test4'
repo_url: 'https://github.com/dcaddick/gsd_test4'
nav:
    - Home: index.md
theme:
  name: 'material'
